### PR TITLE
update maybe dependency

### PR DESCRIPTION
**Pull request by justinwoo**
The purescript-maybe dependency needs to be upgraded to work with some other packages

### CODE REVIEW

**Comment by joneshf** [comment]
Thanks! I've added you as a collaborator. You should merge this when you feel it's ready.

**Comment by justinwoo** [comment]
could you push a release? i'm going to try to update purescript-simple-request off of this next

**Comment by joneshf** [comment]
I forget that things aren't documented and this still uses gulp :blush:.

1. Run one of these commands: https://github.com/joneshf/purescript-http/blob/4f0f790e8e87a88a3719830b38d6519cc1d65672/gulpfile.js#L50-L58 depending on which change you want.
1. Push the commit/tag. 
1. Bower picks up the tag as a new release.

**Comment by justinwoo** [comment]
I think a lot of these deps are too ancient by now... I just get various forms of `require.extensions.hasOwnProperty is not a function` when I try to run gulp 😦

**Comment by justinwoo** [comment]
What would we lose with simply using Pulp publishing? Should we do that instead?

**Comment by joneshf** [comment]
Nothing would be lost. Just haven't updated.

**Comment by joneshf** [comment]
It's up now: https://pursuit.purescript.org/packages/purescript-http/3.0.0

**Comment by justinwoo** [comment]
Thanks!

**Pull request merged**
